package com.expedia.bookings.enums;

public enum ResultsFlightsState {
	LOADING,
	SEARCH_ERROR,
	FLIGHT_LIST_DOWN,
	CHOOSING_FLIGHT,
	ADDING_FLIGHT_TO_TRIP,
	NO_FLIGHTS_DROPDOWN_POS,
	NO_FLIGHTS_POS,
	MISSING_ORIGIN,
	MISSING_STARTDATE
}
