package com.expedia.bookings.enums;

public enum ResultsHotelsState {
	LOADING,
	SEARCH_ERROR,
	HOTEL_LIST_DOWN,
	HOTEL_LIST_UP,
	HOTEL_LIST_AND_FILTERS,
	ROOMS_AND_RATES,
	REVIEWS,
	ROOMS_AND_RATES_FILTERS,
	ADDING_HOTEL_TO_TRIP,
}
