package com.expedia.bookings.enums;

public enum ResultsFlightsState {
	LOADING,
	FLIGHT_HISTOGRAM,
	FLIGHT_LIST_DOWN,
	FLIGHT_ONE_FILTERS,
	FLIGHT_ONE_DETAILS,
	FLIGHT_TWO_FILTERS,
	FLIGHT_TWO_DETAILS,
	ADDING_FLIGHT_TO_TRIP
}
